version: 0.2

phases:
  build:
    command:
      - ./gradlew build
      - docker run --rm \
          -v $(pwd):/app \
          -w /app \
          openjdk:11.0.11-jre-slim-buster sh \
          -c "./gradlew build"\