version: 0.2

env:
  variables:
    BASE_IMAGE: "openjdk:11.0.11-jdk-slim-buster"
phases:
  pre_build:
    commands:
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-9)
      - $(aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI})
  build:
    commands:
      - docker container run -i --rm -v $(pwd):/app -w /app ${BASE_IMAGE} sh -c "./gradlew build"
      - docker image build --no-cache -t ${REPOSITORY_URI}:latest .
      - docker image tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker image push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker image push ${REPOSITORY_URI}:latest